name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy (deny warnings)
      run: cargo clippy -- -D warnings
    - name: Format (check only)
      run: cargo fmt --all -- --check
    - name: Build docs (no deps)
      run: cargo doc --no-deps

  msrv:
    name: MSRV 1.88
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
      - name: Build (MSRV)
        run: cargo build -v
      - name: Test (MSRV)
        run: cargo test -v
